// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTRq0zXupBOPeFJ_gslkkC8-UKFkyZFw',
    appId: '1:522416738037:android:90f9dea1a93b5ff438ffbc',
    messagingSenderId: '522416738037',
    projectId: 'citasya-bae2c',
    storageBucket: 'citasya-bae2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvTRq0zXupBOPeFJ_gslkkC8-UKFkyZFw',
    appId: '1:522416738037:ios:90f9dea1a93b5ff438ffbc',
    messagingSenderId: '522416738037',
    projectId: 'citasya-bae2c',
    storageBucket: 'citasya-bae2c.firebasestorage.app',
    iosBundleId: 'digital.clubemkt.citasya',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTRq0zXupBOPeFJ_gslkkC8-UKFkyZFw',
    appId: '1:522416738037:web:90f9dea1a93b5ff438ffbc',
    messagingSenderId: '522416738037',
    projectId: 'citasya-bae2c',
    authDomain: 'citasya-bae2c.firebaseapp.com',
    storageBucket: 'citasya-bae2c.firebasestorage.app',
    measurementId: 'G-DVZ7E6JWF0',
  );

}